### ISSUE TITLE
apps/microbench/src/bench.c 内调用printf打印时未遵守格式限定符约定

### ISSUE THREAD

**Issue by azure-crab** [NJU-ProjectN/nexus-am#4]
printf打印测试用时和分数时，使用"%d"格式限定符，但参数是(unsigned int)的类型。
如：
91        printf("  min time: %d ms [%d]\n", (unsigned int)msec, (unsigned int)cur);
这样，printf实现只能将可变参数解释为int，如果此时恰好由于运行时间过长超过INT_MAX，那么就会导致打印出负数。

**Comment by sashimi-yzh** [comment]
一般不會運行這麼長時間
